every 60 seconds:
	if (공지} >=4
		delete {공지}
		stop
	if {공지} is not set:
		set {공지} to 1
		broadcast "&2서버에서는 메너를 지켜주세요, 뭐 여러분들에게는 당연한 것 이겠죠?"
		stop
	if {공지} is 1:
		set {공지} to 2
		broadcast "&2공지는 1분마다 올라옵니다!"
		stop
	if {공지} is 2:
		set {공지} to 3
		broadcast "&2서버를 태러하는 행위는 자제해주세요!"
		stop
	if {공지} is 3:
		set {공지} to 4
		broadcast "&2서버 규칙에 위반되는 행동을 하면 밴을 당할 수 있어요!"
		stop
	if {공지} is 4:
		delete {공지사항}
		broadcast "&2채팅 메너를 준수해 주세요!"
		stop